version: '3.0'
services:
    jmeter:
        image: jmeter
        container_name: jmeter
        ulimits:
            nproc: 
                soft: 64000
                hard: 64000
            nofile:
                soft: 4096
                hard: 4096
        sysctls:
            net.core.somaxconn: 40000
            net.ipv4.tcp_max_syn_backlog: 40000
            net.ipv4.tcp_window_scaling: 1
            net.ipv4.tcp_keepalive_probes: 2
            net.ipv4.tcp_keepalive_intvl: 20
            net.ipv4.tcp_fin_timeout: 15
            net.ipv4.tcp_keepalive_time: 300
            net.ipv4.tcp_tw_reuse: 1        
            net.ipv4.tcp_sack: 1
            net.ipv4.tcp_syncookies: 1
            net.ipv4.ip_local_port_range: 1025 65000
        volumes:
            - <Path to the Apache JMeter Test Case>:/home/data